# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a4f8ed75eda3cc8abd52e5ffd433c83d3da5e22d06f5545a4468db3f4bee8e3a3152ce151e68cee063c5ee9dc3119d3842b1d8bb993da7d8968d9df39d9f9d1

test:
  secret_key_base: 5de027e739bc4ebc7930eb791696b55f4a539b68b9f63fc10d889cbd178f308efb5ca787f4a4ca91f3ddf1f65debcc888906b4d15f9d7f8138196c904b53c3c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
